site_name: Build Version
theme:
    name: brtheme
    
docs_dir: docs

plugins:
    - br-as-help-index-gen:
        HelpID: TS_BuildVersion
        ComponentName: BuildVersion
        Version: 1.0.0.0
        ParentGuid: 982bdaef-8fd0-40bd-a348-c999b1816a79
        TargetPath: technologysolutions\ts_buildversionhelp
        OutputPath: ../CICD/

markdown_extensions:
    - admonition
    - pymdownx.details

nav:
    - Build Version: 
        - Build Version: 'index.md'
        - Build Version Task:
            - Build Version Task: 'BuildVersionTask/index.md'
            - Installation: 'BuildVersionTask/WithFrameworkImporterHelp.md'
            - Common Errors: 'BuildVersionTask/CommonErrors.md'
            - Build Warnings: 'BuildVersionTask/BuildWarnings.md'
            - Pre-build Script Options: 'BuildVersionTask/ScriptOptions.md'
        - Widget library: 'MpViewWidgetLibrary/index.md'
